name: Test Zscaler Script

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
          shellcheck zscaler-mac.sh
          find _test -name "*.bash" -o -name "*.bats" | xargs shellcheck || true

  test:
    needs: shellcheck
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install BATS
        run: |
          brew install bats-core

      - name: Create mock certificate directory
        run: |
          mkdir -p "$HOME/.zscalerCerts"
          touch "$HOME/.zscalerCerts/ZscalerRootCA.pem"
          touch "$HOME/.zscalerCerts/ZscalerIntermediateCA.pem"

      - name: Run tests
        run: |
          which bats
          bats --version
          ./_test/run_tests.sh

      - name: Test help command
        run: |
          ./zscaler-mac.sh --help

      - name: Test dry run
        run: |
          ./zscaler-mac.sh --dry-run --azure-cli --profile
